name: Publish release

on:
  push:
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
        shell: bash

      - name: Get version
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Get version on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $VERSION = node -p "require('./package.json').version"
          echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          prerelease: ${{ github.ref == 'refs/heads/dev' }}
          generate_release_notes: true
          files: |
            release/${{ env.VERSION }}/Packager*
            release/${{ env.VERSION }}/latest*